version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./container/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: myphp:latest
        volumes:
            - ./:/var/www/html
        networks:
            - code-network
    mysql:
        image: mysql:latest
        volumes:
            - /mnt/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=php -r "echo (include('config.php'))['mysql_password'];"
            - MYSQL_DATABASE="taskdb"
        networks:
            - code-network
#
networks:
    code-network:
        driver: bridge